export const FETCH_HEALING_PLAN_SUCCESS = 'FETCH_HEALING_PLAN_SUCCESS';
export const ADD_PROCEDURE_TO_PLAN_SUCCESS = 'ADD_PROCEDURE_TO_PLAN_SUCCESS';
export const REMOVE_PROCEDURE_FROM_PLAN_SUCCESS = 'REMOVE_PROCEDURE_FROM_PLAN_SUCCESS';

export const SEND_ATTENDANCE_DATA_SUCCESS = "SEND_ATTENDANCE_DATA_SUCCESS";
export const FETCH_ATTENDANCE_DATA_SUCCESS = "FETCH_ATTENDANCE_DATA_SUCCESS";